camel:
  springboot:
    main-run-controller: true
    tracing: false
  servlet:
    mapping:
      context-path: /api/*
  component:
    aws2-s3:
      override-endpoint: ...
      bucket: ...
      region: ...
  route:
    common: direct:commonOperations

mobidam:
  limit:
    search:
      items: 20
    download: 30
  s3:
    bucket-credential-config:
      x-itmkm82k:
        access-key-env-var: MOBIDAM_X-ITMKM82K_ACCESS_KEY
        secret-key-env-var: MOBIDAM_X-ITMKM82K_SECRET_KEY
      int-mdasc-mdasdev:
        access-key-env-var: MOBIDAM_INT-MDASC-MDASDEV_ACCESS_KEY
        secret-key-env-var: MOBIDAM_INT-MDASC-MDASDEV_SECRET_KEY

spring:
  application:
    name: @project.artifactId@

# https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  info:
    env:
      enabled: true
    camel:
      enabled: false

info:
  application:
    name: @project.artifactId@
    version: @project.version@

