camel:
  springboot:
    main-run-controller: true
    tracing: false
  servlet:
    mapping:
      context-path: /api/*
  component:
    aws2-s3:
      override-endpoint: ...
      region: ...
  route:
    common: direct:commonOperations

mobidam:
  archive:
    expiration-months: 1
  limit:
    search:
      items: 20
  download:
    expiration: 30
  s3:
    bucket-credential-config:
      x-itmkm82k:
        access-key-env-var: MOBIDAM_X-ITMKM82K_ACCESS_KEY
        secret-key-env-var: MOBIDAM_X-ITMKM82K_SECRET_KEY
      int-mdasc-mdasdev:
        access-key-env-var: MOBIDAM_INT-MDASC-MDASDEV_ACCESS_KEY
        secret-key-env-var: MOBIDAM_INT-MDASC-MDASDEV_SECRET_KEY

spring:
  application:
    name: @project.artifactId@
  datasource:
    url: ...
    username: ...
    password: ...
    driver-class-name: ...
  jpa:
    hibernate:
      # always drop and create the db should be the best
      # configuration for local (development) mode. this
      # is also the default, that spring offers by convention.
      # but here explicite:
      ddl-auto: none
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # Logging for database operation
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: ...

# https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  info:
    env:
      enabled: true
    camel:
      enabled: false

info:
  application:
    name: @project.artifactId@
    version: @project.version@

