camel:
  springboot:
    main-run-controller: true
    tracing: false
  servlet:
    mapping:
      context-path: /api/*
  component:
    aws2-s3:
      override-endpoint:
      region:
  route:
    common: direct:commonOperations

mobidam:
  limit:
    search:
      items: 20

spring:
  application:
    name: @project.artifactId@

# https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  info:
    env:
      enabled: true
    camel:
      enabled: false

info:
  application:
    name: @project.artifactId@
    version: @project.version@

