camel:
  springboot:
    main-run-controller: true
    tracing: false
  servlet:
    mapping:
      context-path: /api/*
  component:
    aws2-s3:
      override-endpoint: ...
      region: ...
  route:
    common: direct:commonOperations
    delete-archive: quartz://mobidam/archiveCleanUp?cron=0+30+2+?+*+*

mobidam:
  archive:
    expiration-months: 1
  limit:
    search:
      items: 20
  download:
    expiration: 30
  s3:
    bucket-credential-config:
      x-itmkm82k:
        access-key-env-var: MOBIDAM_ACCESS_KEY
        secret-key-env-var: MOBIDAM_SECRET_KEY
      int-mdasc-mdasdev:
        access-key-env-var: MOBIDAM_ACCESS_KEY
        secret-key-env-var: MOBIDAM_SECRET_KEY
      int-mdask-lapas:
        access-key-env-var: MOBIDAM_ACCESS_KEY
        secret-key-env-var: MOBIDAM_SECRET_KEY

spring:
  application:
    name: @project.artifactId@
  datasource:
    url: ...
    username: ...
    password: ...
    driver-class-name: ...
  jpa:
    hibernate:
      # always drop and create the db should be the best
      # configuration for local (development) mode. this
      # is also the default, that spring offers by convention.
      # but here explicite:
      ddl-auto: none
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # Logging for database operation
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: ...
  quartz:
    job-store-type: memory
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${realm}
          jwk-set-uri: ${keycloak.auth-server-url}/realms/${realm}/protocol/openid-connect/certs

realm: ...
keycloak.auth-server-url: ...

# https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  info:
    env:
      enabled: true
    camel:
      enabled: false

info:
  application:
    name: @project.artifactId@
    version: @project.version@

