openapi: 3.0.3
info:
  title: S3-EAI API
  version: v1
tags:
- name: S3
  description: Files related operations
servers:
- url: https://localhost:8080
components:
  schemas:
    BucketContent:
      type: array
      items:
        type: object
        properties:
          key:
            type: string
          lastmodified:
            type: string
          size:
            type: number
    PresignedUrl:
      type: object
      properties:
        url:
          type: string
          description: Download Url  
    ErrorResponse:
      type: object
      properties:
          timestamp:
            type: string
            format: date-time
          error:
            type: string
          status:
            type: number
paths:
  /filesInFolder:
    get:
      tags:
      - S3
      description: Get S3 bucket object list
      parameters:
      - name: bucketName
        description: Bucket name
        in: query
        schema:
          type: string
          example: MyBucketName
        required: true
      - name: path
        description: S3 path
        in: query
        schema:
          type: string
          example: MyPathName
        required: false  
      responses:
        '200':
          description: Bucket content
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/BucketContent'
        '40X':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '50X':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /presignedUrl:
    get:
      description: Retrieve download link
      tags: 
        - Files
      operationId: viewObjectDownloadLink
      parameters:
      - name: bucketName
        description: Bucket name
        in: query
        schema:
          type: string
          example: MyBucketName
        required: true
      - name: objectName
        description: Object name
        in: query
        schema:
          type: string
          example: MyObjectName
        required: true  
      - name: path
        description: S3 path/prefix
        in: query
        schema:
          type: string
          example: MyPathName
        required: false 
      responses:
        '200':
          description: Download url 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PresignedUrl'