openapi: 3.0.3
info:
  title: S3-EAI API
  version: v1
tags:
  - name: S3
    description: Files related operations
servers:
  - url: https://localhost:8080
components:
  schemas:
    BucketContent:
      type: array
      items:
        type: object
        properties:
          key:
            type: string
          lastmodified:
            type: string
          size:
            type: number
    PresignedUrl:
      type: object
      properties:
        url:
          type: string
          description: Download Url
    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        error:
          type: string
        status:
          type: number
paths:
  /filesInFolder:
    get:
      tags:
        - Bucket
      operationId: viewFilesInFolder
      summary: Get S3 bucket object list
      description: "Each department has its own S3 bucket."
      parameters:
        - name: bucketName
          description: Bucket name
          in: query
          schema:
            type: string
            example: MyBucketName
          required: true
        - name: archive
          description: Move file to bucket 'archive'
          in: query
          schema:
            type: boolean
            example: true
          required: false
      responses:
        '200':
          description: Bucket content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BucketContent'
        4XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        5XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /presignedUrl:
    get:
      summary: Retrieve download link
      description: "Download file, process file, archive file."
      tags:
        - Files
      operationId: viewObjectDownloadLink
      parameters:
        - name: bucketName
          description: Bucket name
          in: query
          schema:
            type: string
            example: MyBucketName
          required: true
        - name: objectName
          description: Object name
          in: query
          schema:
            type: string
            example: MyObjectName
          required: true
      responses:
        '200':
          description: Download url
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PresignedUrl'
        4XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        5XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /archive:
    put:
      tags: 
        - Files
      summary: Move 'processed' file to archive.
      description: "'archive' is tenant wide constant for all buckets"
      operationId: moveFinishedFileToArchive
      parameters:
        - name: bucketName
          description: Bucket name
          in: query
          schema:
            type: string
            example: MyBucketName
          required: true
        - name: objectName
          description: Object name
          in: query
          schema:
            type: string
            example: MyObjectName
          required: true
      responses:
        '204':
          description: File is moved to archive
        4XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        5XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
