openapi: 3.0.3
info:
  title: S3-EAI API
  version: v1
servers:
- url: https://localhost:8080
paths: 
  /filesInFolder:
    get:
      description: Get S3 bucket object list
      parameters:
      - name: bucketName
        description: Bucket name
        in: query
        schema:
          type: string
          example: MyBucketName
        required: true
      responses:
        '200':
          description: Bucket content
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    key:
                      type: string
                    lastmodified:
                      type: string
                    size:
                      type: number
                      
                